package com.dladukedev.bibleyeartracker.bibleReading.display

import androidx.annotation.StringRes
import com.dladukedev.bibleyeartracker.R
import com.dladukedev.bibleyeartracker.bibleReading.domain.BibleBook

object BibleBookNameLookup {
    @StringRes
    fun getBibleNameString(book: BibleBook): Int {
        return books[book]!!
    }

    private val books = mapOf(
        Pair(BibleBook.GENESIS, R.string.genesis),
        Pair(BibleBook.EXODUS, R.string.exodus),
        Pair(BibleBook.LEVITICUS, R.string.leviticus),
        Pair(BibleBook.NUMBERS, R.string.numbers),
        Pair(BibleBook.DEUTERONOMY, R.string.deuteronomy),
        Pair(BibleBook.JOSHUA, R.string.joshua),
        Pair(BibleBook.JUDGES, R.string.judges),
        Pair(BibleBook.RUTH, R.string.ruth),
        Pair(BibleBook.FIRST_SAMUEL, R.string.first_samuel),
        Pair(BibleBook.SECOND_SAMUEL, R.string.second_samuel),
        Pair(BibleBook.FIRST_KINGS, R.string.first_kings),
        Pair(BibleBook.SECOND_KINGS, R.string.second_kings),
        Pair(BibleBook.FIRST_CHRONICLES, R.string.first_chronicles),
        Pair(BibleBook.SECOND_CHRONICLES, R.string.second_chronicles),
        Pair(BibleBook.EZRA, R.string.ezra),
        Pair(BibleBook.NEHEMIAH, R.string.nehemiah),
        Pair(BibleBook.TOBIT, R.string.tobit),
        Pair(BibleBook.JUDITH, R.string.judith),
        Pair(BibleBook.ESTHER, R.string.esther),
        Pair(BibleBook.FIRST_MACCABEES, R.string.first_maccabees),
        Pair(BibleBook.SECOND_MACCABEES, R.string.second_maccabees),
        Pair(BibleBook.JOB, R.string.job),
        Pair(BibleBook.PSALMS, R.string.psalms),
        Pair(BibleBook.PROVERBS, R.string.proverbs),
        Pair(BibleBook.ECCLESIASTES, R.string.ecclesiastes),
        Pair(BibleBook.SONG_OF_SONGS, R.string.song_of_songs),
        Pair(BibleBook.WISDOM, R.string.wisdom),
        Pair(BibleBook.SIRACH, R.string.sirach),
        Pair(BibleBook.ISAIAH, R.string.isaiah),
        Pair(BibleBook.JEREMIAH, R.string.jeremiah),
        Pair(BibleBook.LAMENTATIONS, R.string.lamentations),
        Pair(BibleBook.BARUCH, R.string.baruch),
        Pair(BibleBook.EZEKIEL, R.string.ezekiel),
        Pair(BibleBook.DANIEL, R.string.daniel),
        Pair(BibleBook.HOSEA, R.string.hosea),
        Pair(BibleBook.JOEL, R.string.joel),
        Pair(BibleBook.AMOS, R.string.amos),
        Pair(BibleBook.OBADIAH, R.string.obadiah),
        Pair(BibleBook.JONAH, R.string.jonah),
        Pair(BibleBook.MICAH, R.string.micah),
        Pair(BibleBook.NAHUM, R.string.nahum),
        Pair(BibleBook.HABAKKUK, R.string.habakkuk),
        Pair(BibleBook.ZEPHANIAH, R.string.zephaniah),
        Pair(BibleBook.HAGGAI, R.string.haggai),
        Pair(BibleBook.ZECHARIAH, R.string.zechariah),
        Pair(BibleBook.MALACHI, R.string.malachi),
        Pair(BibleBook.MATTHEW, R.string.matthew),
        Pair(BibleBook.MARK, R.string.mark),
        Pair(BibleBook.LUKE, R.string.luke),
        Pair(BibleBook.JOHN, R.string.john),
        Pair(BibleBook.ACTS, R.string.acts),
        Pair(BibleBook.ROMANS, R.string.romans),
        Pair(BibleBook.FIRST_CORINTHIANS, R.string.first_corinthians),
        Pair(BibleBook.SECOND_CORINTHIANS, R.string.second_corinthians),
        Pair(BibleBook.GALATIANS, R.string.galatians),
        Pair(BibleBook.EPHESIANS, R.string.ephesians),
        Pair(BibleBook.PHILIPPIANS, R.string.philippians),
        Pair(BibleBook.COLOSSIANS, R.string.colossians),
        Pair(BibleBook.FIRST_THESSALONIANS, R.string.first_thessalonians),
        Pair(BibleBook.SECOND_THESSALONIANS, R.string.second_thessalonians),
        Pair(BibleBook.FIRST_TIMOTHY, R.string.first_timothy),
        Pair(BibleBook.SECOND_TIMOTHY, R.string.second_timothy),
        Pair(BibleBook.TITUS, R.string.titus),
        Pair(BibleBook.PHILEMON, R.string.philemon),
        Pair(BibleBook.HEBREWS, R.string.hebrews),
        Pair(BibleBook.JAMES, R.string.james),
        Pair(BibleBook.FIRST_PETER, R.string.first_peter),
        Pair(BibleBook.SECOND_PETER, R.string.second_peter),
        Pair(BibleBook.FIRST_JOHN, R.string.first_john),
        Pair(BibleBook.SECOND_JOHN, R.string.second_john),
        Pair(BibleBook.THIRD_JOHN, R.string.third_john),
        Pair(BibleBook.JUDE, R.string.jude),
        Pair(BibleBook.REVELATION, R.string.revelation),
    )
}