package com.dladukedev.bibleyeartracker.bibleReading.display

import com.dladukedev.bibleyeartracker.R
import com.dladukedev.bibleyeartracker.bibleReading.domain.BibleBook
import org.junit.Assert
import org.junit.Test

class BibleBookNameLookupTest {
    @Test
    fun `getBibleNameString returns the expected resource value`() {
        val genesis = BibleBookNameLookup.getBibleNameString(BibleBook.GENESIS)
        val exodus = BibleBookNameLookup.getBibleNameString(BibleBook.EXODUS)
        val leviticus = BibleBookNameLookup.getBibleNameString(BibleBook.LEVITICUS)
        val numbers = BibleBookNameLookup.getBibleNameString(BibleBook.NUMBERS)
        val deuteronomy = BibleBookNameLookup.getBibleNameString(BibleBook.DEUTERONOMY)
        val joshua = BibleBookNameLookup.getBibleNameString(BibleBook.JOSHUA)
        val judges = BibleBookNameLookup.getBibleNameString(BibleBook.JUDGES)
        val ruth = BibleBookNameLookup.getBibleNameString(BibleBook.RUTH)
        val firstSamuel = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_SAMUEL)
        val secondSamuel = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_SAMUEL)
        val firstKings = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_KINGS)
        val secondKings = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_KINGS)
        val firstChronicles = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_CHRONICLES)
        val secondChronicles = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_CHRONICLES)
        val ezra = BibleBookNameLookup.getBibleNameString(BibleBook.EZRA)
        val nehemiah = BibleBookNameLookup.getBibleNameString(BibleBook.NEHEMIAH)
        val tobit = BibleBookNameLookup.getBibleNameString(BibleBook.TOBIT)
        val judith = BibleBookNameLookup.getBibleNameString(BibleBook.JUDITH)
        val esther = BibleBookNameLookup.getBibleNameString(BibleBook.ESTHER)
        val firstMaccabees = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_MACCABEES)
        val secondMaccabees = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_MACCABEES)
        val job = BibleBookNameLookup.getBibleNameString(BibleBook.JOB)
        val psalms = BibleBookNameLookup.getBibleNameString(BibleBook.PSALMS)
        val proverbs = BibleBookNameLookup.getBibleNameString(BibleBook.PROVERBS)
        val ecclesiastes = BibleBookNameLookup.getBibleNameString(BibleBook.ECCLESIASTES)
        val songOfSongs = BibleBookNameLookup.getBibleNameString(BibleBook.SONG_OF_SONGS)
        val wisdom = BibleBookNameLookup.getBibleNameString(BibleBook.WISDOM)
        val sirach = BibleBookNameLookup.getBibleNameString(BibleBook.SIRACH)
        val isaiah = BibleBookNameLookup.getBibleNameString(BibleBook.ISAIAH)
        val jeremiah = BibleBookNameLookup.getBibleNameString(BibleBook.JEREMIAH)
        val lamentations = BibleBookNameLookup.getBibleNameString(BibleBook.LAMENTATIONS)
        val baruch = BibleBookNameLookup.getBibleNameString(BibleBook.BARUCH)
        val ezekiel = BibleBookNameLookup.getBibleNameString(BibleBook.EZEKIEL)
        val daniel = BibleBookNameLookup.getBibleNameString(BibleBook.DANIEL)
        val hosea = BibleBookNameLookup.getBibleNameString(BibleBook.HOSEA)
        val joel = BibleBookNameLookup.getBibleNameString(BibleBook.JOEL)
        val amos = BibleBookNameLookup.getBibleNameString(BibleBook.AMOS)
        val obadiah = BibleBookNameLookup.getBibleNameString(BibleBook.OBADIAH)
        val jonah = BibleBookNameLookup.getBibleNameString(BibleBook.JONAH)
        val micah = BibleBookNameLookup.getBibleNameString(BibleBook.MICAH)
        val nahum = BibleBookNameLookup.getBibleNameString(BibleBook.NAHUM)
        val habakkuk = BibleBookNameLookup.getBibleNameString(BibleBook.HABAKKUK)
        val zephaniah = BibleBookNameLookup.getBibleNameString(BibleBook.ZEPHANIAH)
        val haggai = BibleBookNameLookup.getBibleNameString(BibleBook.HAGGAI)
        val zechariah = BibleBookNameLookup.getBibleNameString(BibleBook.ZECHARIAH)
        val malachi = BibleBookNameLookup.getBibleNameString(BibleBook.MALACHI)
        val matthew = BibleBookNameLookup.getBibleNameString(BibleBook.MATTHEW)
        val mark = BibleBookNameLookup.getBibleNameString(BibleBook.MARK)
        val luke = BibleBookNameLookup.getBibleNameString(BibleBook.LUKE)
        val john = BibleBookNameLookup.getBibleNameString(BibleBook.JOHN)
        val acts = BibleBookNameLookup.getBibleNameString(BibleBook.ACTS)
        val romans = BibleBookNameLookup.getBibleNameString(BibleBook.ROMANS)
        val firstCorinthians = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_CORINTHIANS)
        val secondCorinthians = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_CORINTHIANS)
        val galatians = BibleBookNameLookup.getBibleNameString(BibleBook.GALATIANS)
        val ephesians = BibleBookNameLookup.getBibleNameString(BibleBook.EPHESIANS)
        val philippians = BibleBookNameLookup.getBibleNameString(BibleBook.PHILIPPIANS)
        val colossians = BibleBookNameLookup.getBibleNameString(BibleBook.COLOSSIANS)
        val firstThessalonians = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_THESSALONIANS)
        val secondThessalonians = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_THESSALONIANS)
        val firstTimothy = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_TIMOTHY)
        val secondTimothy = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_TIMOTHY)
        val titus = BibleBookNameLookup.getBibleNameString(BibleBook.TITUS)
        val philemon = BibleBookNameLookup.getBibleNameString(BibleBook.PHILEMON)
        val hebrews = BibleBookNameLookup.getBibleNameString(BibleBook.HEBREWS)
        val james = BibleBookNameLookup.getBibleNameString(BibleBook.JAMES)
        val firstPeter = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_PETER)
        val secondPeter = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_PETER)
        val firstJohn = BibleBookNameLookup.getBibleNameString(BibleBook.FIRST_JOHN)
        val secondJohn = BibleBookNameLookup.getBibleNameString(BibleBook.SECOND_JOHN)
        val thirdJohn = BibleBookNameLookup.getBibleNameString(BibleBook.THIRD_JOHN)
        val jude = BibleBookNameLookup.getBibleNameString(BibleBook.JUDE)
        val revelation = BibleBookNameLookup.getBibleNameString(BibleBook.REVELATION)

        Assert.assertEquals(genesis, R.string.genesis)
        Assert.assertEquals(exodus, R.string.exodus)
        Assert.assertEquals(leviticus, R.string.leviticus)
        Assert.assertEquals(numbers, R.string.numbers)
        Assert.assertEquals(deuteronomy, R.string.deuteronomy)
        Assert.assertEquals(joshua, R.string.joshua)
        Assert.assertEquals(judges, R.string.judges)
        Assert.assertEquals(ruth, R.string.ruth)
        Assert.assertEquals(firstSamuel, R.string.first_samuel)
        Assert.assertEquals(secondSamuel, R.string.second_samuel)
        Assert.assertEquals(firstKings, R.string.first_kings)
        Assert.assertEquals(secondKings, R.string.second_kings)
        Assert.assertEquals(firstChronicles, R.string.first_chronicles)
        Assert.assertEquals(secondChronicles, R.string.second_chronicles)
        Assert.assertEquals(ezra, R.string.ezra)
        Assert.assertEquals(nehemiah, R.string.nehemiah)
        Assert.assertEquals(tobit, R.string.tobit)
        Assert.assertEquals(judith, R.string.judith)
        Assert.assertEquals(esther, R.string.esther)
        Assert.assertEquals(firstMaccabees, R.string.first_maccabees)
        Assert.assertEquals(secondMaccabees, R.string.second_maccabees)
        Assert.assertEquals(job, R.string.job)
        Assert.assertEquals(psalms, R.string.psalms)
        Assert.assertEquals(proverbs, R.string.proverbs)
        Assert.assertEquals(ecclesiastes, R.string.ecclesiastes)
        Assert.assertEquals(songOfSongs, R.string.song_of_songs)
        Assert.assertEquals(wisdom, R.string.wisdom)
        Assert.assertEquals(sirach, R.string.sirach)
        Assert.assertEquals(isaiah, R.string.isaiah)
        Assert.assertEquals(jeremiah, R.string.jeremiah)
        Assert.assertEquals(lamentations, R.string.lamentations)
        Assert.assertEquals(baruch, R.string.baruch)
        Assert.assertEquals(ezekiel, R.string.ezekiel)
        Assert.assertEquals(daniel, R.string.daniel)
        Assert.assertEquals(hosea, R.string.hosea)
        Assert.assertEquals(joel, R.string.joel)
        Assert.assertEquals(amos, R.string.amos)
        Assert.assertEquals(obadiah, R.string.obadiah)
        Assert.assertEquals(jonah, R.string.jonah)
        Assert.assertEquals(micah, R.string.micah)
        Assert.assertEquals(nahum, R.string.nahum)
        Assert.assertEquals(habakkuk, R.string.habakkuk)
        Assert.assertEquals(zephaniah, R.string.zephaniah)
        Assert.assertEquals(haggai, R.string.haggai)
        Assert.assertEquals(zechariah, R.string.zechariah)
        Assert.assertEquals(malachi, R.string.malachi)
        Assert.assertEquals(matthew, R.string.matthew)
        Assert.assertEquals(mark, R.string.mark)
        Assert.assertEquals(luke, R.string.luke)
        Assert.assertEquals(john, R.string.john)
        Assert.assertEquals(acts, R.string.acts)
        Assert.assertEquals(romans, R.string.romans)
        Assert.assertEquals(firstCorinthians, R.string.first_corinthians)
        Assert.assertEquals(secondCorinthians, R.string.second_corinthians)
        Assert.assertEquals(galatians, R.string.galatians)
        Assert.assertEquals(ephesians, R.string.ephesians)
        Assert.assertEquals(philippians, R.string.philippians)
        Assert.assertEquals(colossians, R.string.colossians)
        Assert.assertEquals(firstThessalonians, R.string.first_thessalonians)
        Assert.assertEquals(secondThessalonians, R.string.second_thessalonians)
        Assert.assertEquals(firstTimothy, R.string.first_timothy)
        Assert.assertEquals(secondTimothy, R.string.second_timothy)
        Assert.assertEquals(titus, R.string.titus)
        Assert.assertEquals(philemon, R.string.philemon)
        Assert.assertEquals(hebrews, R.string.hebrews)
        Assert.assertEquals(james, R.string.james)
        Assert.assertEquals(firstPeter, R.string.first_peter)
        Assert.assertEquals(secondPeter, R.string.second_peter)
        Assert.assertEquals(firstJohn, R.string.first_john)
        Assert.assertEquals(secondJohn, R.string.second_john)
        Assert.assertEquals(thirdJohn, R.string.third_john)
        Assert.assertEquals(jude, R.string.jude)
        Assert.assertEquals(revelation, R.string.revelation)
    }
}